"""drawings, sheets, tiles

Creates the ingest-pipeline tables. Hand-written (not autogenerated) so
that constraint names, index choices, and cascade behavior are pinned
from the first commit.

Schema notes:

- ``drawings.content_hash`` is indexed to support dedup checks before a
  new pipeline run is enqueued.
- ``drawings.status`` and ``sheets.status`` are plain VARCHARs guarded by
  a CHECK constraint rather than a Postgres ENUM — adding new states in
  later milestones is a one-line constraint update instead of ``ALTER
  TYPE``.
- ``sheets`` and ``tiles`` cascade on drawing deletion so wiping a
  drawing removes everything associated.
- ``tiles`` has a unique (sheet, zoom, col, row) coordinate key; the
  composite ``ix_tiles_sheet_zoom`` index supports the common
  "list all tiles at zoom N for this sheet" query.

Revision ID: 0002_drawings
Revises: 0001_baseline
Create Date: 2026-04-16

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002_drawings"
down_revision: str | None = "0001_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_STATUS_VALUES = ("queued", "validating", "rasterizing", "tiling", "completed", "failed")
_STATUS_CHECK = (
    "status IN ("
    + ", ".join(f"'{s}'" for s in _STATUS_VALUES)
    + ")"
)


def upgrade() -> None:
    op.create_table(
        "drawings",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("project_name", sa.String(length=255), nullable=True),
        sa.Column("source_filename", sa.String(length=512), nullable=False),
        sa.Column("source_s3_key", sa.String(length=1024), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("content_hash", sa.String(length=128), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.String(length=32),
            nullable=False,
            server_default="queued",
        ),
        sa.Column(
            "progress_percent",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
        sa.Column("progress_message", sa.String(length=512), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.String(length=2048), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.CheckConstraint(_STATUS_CHECK, name="ck_drawings_status_valid"),
        sa.CheckConstraint(
            "progress_percent BETWEEN 0 AND 100",
            name="ck_drawings_progress_range",
        ),
    )
    op.create_index("ix_drawings_status", "drawings", ["status"])
    op.create_index("ix_drawings_created_at_desc", "drawings", ["created_at"])
    op.create_index("ix_drawings_content_hash", "drawings", ["content_hash"])
    op.create_index("ix_drawings_project_name", "drawings", ["project_name"])

    op.create_table(
        "sheets",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("drawing_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("sheet_number", sa.String(length=64), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("discipline", sa.String(length=1), nullable=True),
        sa.Column("width_px", sa.Integer(), nullable=True),
        sa.Column("height_px", sa.Integer(), nullable=True),
        sa.Column("dpi", sa.Integer(), nullable=True),
        sa.Column("page_width_pts", sa.Float(), nullable=True),
        sa.Column("page_height_pts", sa.Float(), nullable=True),
        sa.Column("tile_size", sa.Integer(), nullable=True),
        sa.Column("max_zoom", sa.Integer(), nullable=True),
        sa.Column("preview_s3_key", sa.String(length=1024), nullable=True),
        sa.Column(
            "status",
            sa.String(length=32),
            nullable=False,
            server_default="queued",
        ),
        sa.Column(
            "progress_percent",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
        sa.Column("error_message", sa.String(length=2048), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.ForeignKeyConstraint(
            ["drawing_id"],
            ["drawings.id"],
            ondelete="CASCADE",
            name="fk_sheets_drawing_id",
        ),
        sa.UniqueConstraint(
            "drawing_id", "page_number", name="uq_sheets_drawing_page"
        ),
        sa.CheckConstraint(_STATUS_CHECK, name="ck_sheets_status_valid"),
        sa.CheckConstraint(
            "progress_percent BETWEEN 0 AND 100",
            name="ck_sheets_progress_range",
        ),
        sa.CheckConstraint("page_number >= 1", name="ck_sheets_page_number_positive"),
    )
    op.create_index("ix_sheets_status", "sheets", ["status"])
    op.create_index("ix_sheets_drawing_id", "sheets", ["drawing_id"])

    op.create_table(
        "tiles",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("sheet_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("zoom_level", sa.Integer(), nullable=False),
        sa.Column("col", sa.Integer(), nullable=False),
        sa.Column("row", sa.Integer(), nullable=False),
        sa.Column("s3_key", sa.String(length=1024), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column(
            "content_type",
            sa.String(length=64),
            nullable=False,
            server_default="image/webp",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sheet_id"],
            ["sheets.id"],
            ondelete="CASCADE",
            name="fk_tiles_sheet_id",
        ),
        sa.UniqueConstraint(
            "sheet_id", "zoom_level", "col", "row", name="uq_tiles_coord"
        ),
        sa.CheckConstraint("zoom_level >= 0", name="ck_tiles_zoom_nonneg"),
        sa.CheckConstraint(
            "col >= 0 AND row >= 0", name="ck_tiles_coord_nonneg"
        ),
    )
    op.create_index("ix_tiles_sheet_zoom", "tiles", ["sheet_id", "zoom_level"])


def downgrade() -> None:
    op.drop_index("ix_tiles_sheet_zoom", table_name="tiles")
    op.drop_table("tiles")

    op.drop_index("ix_sheets_drawing_id", table_name="sheets")
    op.drop_index("ix_sheets_status", table_name="sheets")
    op.drop_table("sheets")

    op.drop_index("ix_drawings_project_name", table_name="drawings")
    op.drop_index("ix_drawings_content_hash", table_name="drawings")
    op.drop_index("ix_drawings_created_at_desc", table_name="drawings")
    op.drop_index("ix_drawings_status", table_name="drawings")
    op.drop_table("drawings")
